# Generated by Django 3.0.11 on 2020-12-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=225)),
                ('b_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
